### ISSUE TITLE
can you give me the environment andthe configure of your machine

### ISSUE THREAD

**Issue by yaozongbao** [nddsg/KGMiner#26]
what kind of dependency I need to install？ to run the program ，how much memory I need？

**Comment by bxshi** [comment]
Hi, I think all you need is the C++ boost library. You may see an error saying lacking of `librdf++` but that is fine just ignore it (That separate program is used used in this experiment).

As for the memory footprint, I think its less than 10G but you could try on your machine and see how much it actually costs.

Thanks!
